### ISSUE TITLE
[BUG] issue downloading opm from mirror

### ISSUE THREAD

**Issue by tuxtof** [redhat-actions/openshift-tools-installer#112]
### Describe the bug
opm binary have a new name in archive and there is an error when we try to download it

Error: opm executable was not found in opm-linux-4.17.2.tar.gz downloaded from https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.17.2/opm-linux-4.17.2.tar.gz

### Steps to reproduce, workflow links, screenshots

create a task like

```
      - name: Install CLI tools from OpenShift Mirror
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          opm: "latest"
```
