### ISSUE TITLE
[BUG] cannot install s2i versions ≥ 1.4.0

### ISSUE THREAD

**Issue by jmtd** [redhat-actions/openshift-tools-installer#116]
### Version

redhat-actions/openshift-tools-installer@v1.13.1

and s2i > 1.4.0

### Describe the bug

the s2i install only works if the s2i github project has attached binaries to releases. For the latest version (v1.5.0), they've only provided source artefacts. So the following fails:

```yaml
         with:
           source: "github"
           github_pat: ${{ github.token }}
          s2i: "1.5.0"
```

See also https://github.com/openshift/source-to-image/issues/1219
