### ISSUE TITLE
[BUG] Installation from mirror fails

### ISSUE THREAD

**Issue by cpenna** [redhat-actions/openshift-tools-installer#98]
### Version

v1

### Describe the bug
Installation from mirror fails
I noticed a failure to download helm in my env:  `Error: Error: Did not find file "helm-linux-amd64.tar.gz" in the given hash file`
I could also see that `example_mirror.yml` fails during executions [here](https://github.com/redhat-actions/openshift-tools-installer/actions/workflows/example_mirror.yml) as well.

### Steps to reproduce, workflow links, screenshots

I'm using an Ubuntu runner (22.04) on GitHub Enterprise.
```
runs:
  using: composite
  steps:
    - name: Install OpenShift Client
      uses: actions/redhat-actions_openshift-tools-installer@v1
      with:
        oc: "4"
        helm: "3"
```
![image](https://github.com/redhat-actions/openshift-tools-installer/assets/10945999/be75e382-a13d-4f70-a3ed-d25fd878014f)
