### ISSUE TITLE
[BUG] Error installing Helm: File not found in hash file

### ISSUE THREAD

**Issue by kishanTakeda** [redhat-actions/openshift-tools-installer#99]
**Description:**
I encountered an issue while using the redhat-actions/openshift-tools-installer action in my GitHub Actions workflow. The issue seems to be related to the installation of Helm, and I received the following error:

`Error: Error: Error: Did not find file "helm-linux-amd64.tar.gz" in the given hash file`

**Action Context:**
```
    - name: Install CLI tools from OpenShift Mirror
        # https://github.com/redhat-actions/openshift-tools-installer
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          source: "mirror"
          oc: "latest"
          helm: "latest"

```
I could also see that example_mirror.yml fails during executions [here](https://github.com/redhat-actions/openshift-tools-installer/actions/workflows/example_mirror.yml) as well.

![image](https://github.com/redhat-actions/openshift-tools-installer/assets/80945137/9d312dfb-dc0a-4b6b-b70d-1fc5295de77b)
